<?php

/**
 * This is the model base class for the table "archivo.examen_fisico_diagnostico_f08".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamenFisicoDiagnosticoF08".
 *
 * Columns in table "archivo.examen_fisico_diagnostico_f08" available as properties of the model,
 * followed by relations of table "archivo.examen_fisico_diagnostico_f08" available as properties of the model.
 *
 * @property integer $id_exfidi
 * @property boolean $via_aerea_destruida
 * @property string $cabeza
 * @property string $cuello
 * @property string $torax
 * @property string $abdomen
 * @property string $columna
 * @property string $pelvis
 * @property string $extremidad
 * @property string $observacion
 *
 * @property Ficha08[] $ficha08s
 */
abstract class BaseExamenFisicoDiagnosticoF08 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'archivo.examen_fisico_diagnostico_f08';
    }

    public static function representingColumn() {
        return 'cabeza';
    }

    public function rules() {
        return array(
            array('id_exfidi', 'required'),
            array('id_exfidi', 'numerical', 'integerOnly'=>true),
            array('cabeza, cuello, torax, abdomen, columna, pelvis, extremidad', 'length', 'max'=>2),
            array('via_aerea_destruida, observacion', 'safe'),
            array('via_aerea_destruida, cabeza, cuello, torax, abdomen, columna, pelvis, extremidad, observacion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_exfidi, via_aerea_destruida, cabeza, cuello, torax, abdomen, columna, pelvis, extremidad, observacion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ficha08s' => array(self::HAS_MANY, 'Ficha08', 'id_exfidi_f08'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_exfidi' => Yii::t('app', 'Id Exfidi'),
                'via_aerea_destruida' => Yii::t('app', 'Via Aerea Destruida'),
                'cabeza' => Yii::t('app', 'Cabeza'),
                'cuello' => Yii::t('app', 'Cuello'),
                'torax' => Yii::t('app', 'Torax'),
                'abdomen' => Yii::t('app', 'Abdomen'),
                'columna' => Yii::t('app', 'Columna'),
                'pelvis' => Yii::t('app', 'Pelvis'),
                'extremidad' => Yii::t('app', 'Extremidad'),
                'observacion' => Yii::t('app', 'Observacion'),
                'ficha08s' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_exfidi', $this->id_exfidi);
        $criteria->compare('via_aerea_destruida', $this->via_aerea_destruida);
        $criteria->compare('cabeza', $this->cabeza, true);
        $criteria->compare('cuello', $this->cuello, true);
        $criteria->compare('torax', $this->torax, true);
        $criteria->compare('abdomen', $this->abdomen, true);
        $criteria->compare('columna', $this->columna, true);
        $criteria->compare('pelvis', $this->pelvis, true);
        $criteria->compare('extremidad', $this->extremidad, true);
        $criteria->compare('observacion', $this->observacion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}