<?php

/**
 * This is the model base class for the table "archivo.localizacion_lesiones_f08".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LocalizacionLesionesF08".
 *
 * Columns in table "archivo.localizacion_lesiones_f08" available as properties of the model,
 * followed by relations of table "archivo.localizacion_lesiones_f08" available as properties of the model.
 *
 * @property integer $id_localizacion_lesiones
 * @property boolean $herida_penetrante
 * @property boolean $herida_cortante
 * @property boolean $fractura_expuesta
 * @property boolean $fractura_cerrada
 * @property boolean $cuerpo_extrano
 * @property boolean $hemorragia
 * @property boolean $mordedura
 * @property boolean $picadura
 * @property boolean $excoriacion
 * @property boolean $deformidad_masa
 * @property boolean $hematoma
 * @property boolean $eritema_inflamacion
 * @property boolean $luxacion_esguince
 * @property boolean $quemadura
 * @property boolean $otro
 * @property string $definicion_cuerpo
 *
 * @property Ficha08[] $ficha08s
 */
abstract class BaseLocalizacionLesionesF08 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'archivo.localizacion_lesiones_f08';
    }

    public static function representingColumn() {
        return 'definicion_cuerpo';
    }

    public function rules() {
        return array(
            array('id_localizacion_lesiones', 'required'),
            array('id_localizacion_lesiones', 'numerical', 'integerOnly'=>true),
            array('herida_penetrante, herida_cortante, fractura_expuesta, fractura_cerrada, cuerpo_extrano, hemorragia, mordedura, picadura, excoriacion, deformidad_masa, hematoma, eritema_inflamacion, luxacion_esguince, quemadura, otro, definicion_cuerpo', 'safe'),
            array('herida_penetrante, herida_cortante, fractura_expuesta, fractura_cerrada, cuerpo_extrano, hemorragia, mordedura, picadura, excoriacion, deformidad_masa, hematoma, eritema_inflamacion, luxacion_esguince, quemadura, otro, definicion_cuerpo', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_localizacion_lesiones, herida_penetrante, herida_cortante, fractura_expuesta, fractura_cerrada, cuerpo_extrano, hemorragia, mordedura, picadura, excoriacion, deformidad_masa, hematoma, eritema_inflamacion, luxacion_esguince, quemadura, otro, definicion_cuerpo', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ficha08s' => array(self::HAS_MANY, 'Ficha08', 'id_localizacion_lesiones_f08'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_localizacion_lesiones' => Yii::t('app', 'Id Localizacion Lesiones'),
                'herida_penetrante' => Yii::t('app', 'Herida Penetrante'),
                'herida_cortante' => Yii::t('app', 'Herida Cortante'),
                'fractura_expuesta' => Yii::t('app', 'Fractura Expuesta'),
                'fractura_cerrada' => Yii::t('app', 'Fractura Cerrada'),
                'cuerpo_extrano' => Yii::t('app', 'Cuerpo Extrano'),
                'hemorragia' => Yii::t('app', 'Hemorragia'),
                'mordedura' => Yii::t('app', 'Mordedura'),
                'picadura' => Yii::t('app', 'Picadura'),
                'excoriacion' => Yii::t('app', 'Excoriacion'),
                'deformidad_masa' => Yii::t('app', 'Deformidad Masa'),
                'hematoma' => Yii::t('app', 'Hematoma'),
                'eritema_inflamacion' => Yii::t('app', 'Eritema Inflamacion'),
                'luxacion_esguince' => Yii::t('app', 'Luxacion Esguince'),
                'quemadura' => Yii::t('app', 'Quemadura'),
                'otro' => Yii::t('app', 'Otro'),
                'definicion_cuerpo' => Yii::t('app', 'Definicion Cuerpo'),
                'ficha08s' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_localizacion_lesiones', $this->id_localizacion_lesiones);
        $criteria->compare('herida_penetrante', $this->herida_penetrante);
        $criteria->compare('herida_cortante', $this->herida_cortante);
        $criteria->compare('fractura_expuesta', $this->fractura_expuesta);
        $criteria->compare('fractura_cerrada', $this->fractura_cerrada);
        $criteria->compare('cuerpo_extrano', $this->cuerpo_extrano);
        $criteria->compare('hemorragia', $this->hemorragia);
        $criteria->compare('mordedura', $this->mordedura);
        $criteria->compare('picadura', $this->picadura);
        $criteria->compare('excoriacion', $this->excoriacion);
        $criteria->compare('deformidad_masa', $this->deformidad_masa);
        $criteria->compare('hematoma', $this->hematoma);
        $criteria->compare('eritema_inflamacion', $this->eritema_inflamacion);
        $criteria->compare('luxacion_esguince', $this->luxacion_esguince);
        $criteria->compare('quemadura', $this->quemadura);
        $criteria->compare('otro', $this->otro);
        $criteria->compare('definicion_cuerpo', $this->definicion_cuerpo, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}