<?php

/**
 * This is the model base class for the table "archivo.ficha_08".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ficha08".
 *
 * Columns in table "archivo.ficha_08" available as properties of the model,
 * followed by relations of table "archivo.ficha_08" available as properties of the model.
 *
 * @property integer $id_f08
 * @property string $fecha_emision
 * @property integer $id_iam_f08
 * @property integer $id_avieq_f08
 * @property integer $id_apyf_f08
 * @property integer $id_earesi_f08
 * @property integer $id_sivimi_f08
 * @property integer $id_exfidi_f08
 * @property integer $id_localizacion_lesiones_f08
 * @property integer $id_emergencia_obstetrica_f08
 * @property integer $id_solicitud_examenes_f08
 * @property integer $id_diagnostico_ingreso_f08
 * @property integer $id_plan_tratamiento_f08
 * @property integer $id_diagnostico_alta_f08
 * @property integer $id_alta_f08
 *
 * @property AltaF08 $idAltaF08
 * @property AntecedentesPersonalesFamiliaresF08 $idApyfF08
 * @property AvieqF08 $idAvieqF08
 * @property DiagnosticoAltaF08 $idDiagnosticoAltaF08
 * @property DiagnosticoIngresoF08 $idDiagnosticoIngresoF08
 * @property EmergenciaObstetricaF08 $idEmergenciaObstetricaF08
 * @property EnfermedadActualRevisionSistemasF08 $idEaresiF08
 * @property ExamenFisicoDiagnosticoF08 $idExfidiF08
 * @property InicioAtencionMotivoF08 $idIamF08
 * @property LocalizacionLesionesF08 $idLocalizacionLesionesF08
 * @property PlanTratamientoF08 $idPlanTratamientoF08
 * @property SignosVitalesMedicinalesF08 $idSivimiF08
 * @property SolicitudExamenesF08 $idSolicitudExamenesF08
 */
abstract class BaseFicha08 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'archivo.ficha_08';
    }

    public static function representingColumn() {
        return 'fecha_emision';
    }

    public function rules() {
        return array(
            array('id_f08', 'required'),
            array('id_f08, id_iam_f08, id_avieq_f08, id_apyf_f08, id_earesi_f08, id_sivimi_f08, id_exfidi_f08, id_localizacion_lesiones_f08, id_emergencia_obstetrica_f08, id_solicitud_examenes_f08, id_diagnostico_ingreso_f08, id_plan_tratamiento_f08, id_diagnostico_alta_f08, id_alta_f08', 'numerical', 'integerOnly'=>true),
            array('fecha_emision', 'safe'),
            array('fecha_emision, id_iam_f08, id_avieq_f08, id_apyf_f08, id_earesi_f08, id_sivimi_f08, id_exfidi_f08, id_localizacion_lesiones_f08, id_emergencia_obstetrica_f08, id_solicitud_examenes_f08, id_diagnostico_ingreso_f08, id_plan_tratamiento_f08, id_diagnostico_alta_f08, id_alta_f08', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_f08, fecha_emision, id_iam_f08, id_avieq_f08, id_apyf_f08, id_earesi_f08, id_sivimi_f08, id_exfidi_f08, id_localizacion_lesiones_f08, id_emergencia_obstetrica_f08, id_solicitud_examenes_f08, id_diagnostico_ingreso_f08, id_plan_tratamiento_f08, id_diagnostico_alta_f08, id_alta_f08', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idAltaF08' => array(self::BELONGS_TO, 'AltaF08', 'id_alta_f08'),
            'idApyfF08' => array(self::BELONGS_TO, 'AntecedentesPersonalesFamiliaresF08', 'id_apyf_f08'),
            'idAvieqF08' => array(self::BELONGS_TO, 'AvieqF08', 'id_avieq_f08'),
            'idDiagnosticoAltaF08' => array(self::BELONGS_TO, 'DiagnosticoAltaF08', 'id_diagnostico_alta_f08'),
            'idDiagnosticoIngresoF08' => array(self::BELONGS_TO, 'DiagnosticoIngresoF08', 'id_diagnostico_ingreso_f08'),
            'idEmergenciaObstetricaF08' => array(self::BELONGS_TO, 'EmergenciaObstetricaF08', 'id_emergencia_obstetrica_f08'),
            'idEaresiF08' => array(self::BELONGS_TO, 'EnfermedadActualRevisionSistemasF08', 'id_earesi_f08'),
            'idExfidiF08' => array(self::BELONGS_TO, 'ExamenFisicoDiagnosticoF08', 'id_exfidi_f08'),
            'idIamF08' => array(self::BELONGS_TO, 'InicioAtencionMotivoF08', 'id_iam_f08'),
            'idLocalizacionLesionesF08' => array(self::BELONGS_TO, 'LocalizacionLesionesF08', 'id_localizacion_lesiones_f08'),
            'idPlanTratamientoF08' => array(self::BELONGS_TO, 'PlanTratamientoF08', 'id_plan_tratamiento_f08'),
            'idSivimiF08' => array(self::BELONGS_TO, 'SignosVitalesMedicinalesF08', 'id_sivimi_f08'),
            'idSolicitudExamenesF08' => array(self::BELONGS_TO, 'SolicitudExamenesF08', 'id_solicitud_examenes_f08'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_f08' => Yii::t('app', 'Id F08'),
                'fecha_emision' => Yii::t('app', 'Fecha Emision'),
                'id_iam_f08' => Yii::t('app', 'Id Iam F08'),
                'id_avieq_f08' => Yii::t('app', 'Id Avieq F08'),
                'id_apyf_f08' => Yii::t('app', 'Id Apyf F08'),
                'id_earesi_f08' => Yii::t('app', 'Id Earesi F08'),
                'id_sivimi_f08' => Yii::t('app', 'Id Sivimi F08'),
                'id_exfidi_f08' => Yii::t('app', 'Id Exfidi F08'),
                'id_localizacion_lesiones_f08' => Yii::t('app', 'Id Localizacion Lesiones F08'),
                'id_emergencia_obstetrica_f08' => Yii::t('app', 'Id Emergencia Obstetrica F08'),
                'id_solicitud_examenes_f08' => Yii::t('app', 'Id Solicitud Examenes F08'),
                'id_diagnostico_ingreso_f08' => Yii::t('app', 'Id Diagnostico Ingreso F08'),
                'id_plan_tratamiento_f08' => Yii::t('app', 'Id Plan Tratamiento F08'),
                'id_diagnostico_alta_f08' => Yii::t('app', 'Id Diagnostico Alta F08'),
                'id_alta_f08' => Yii::t('app', 'Id Alta F08'),
                'idAltaF08' => null,
                'idApyfF08' => null,
                'idAvieqF08' => null,
                'idDiagnosticoAltaF08' => null,
                'idDiagnosticoIngresoF08' => null,
                'idEmergenciaObstetricaF08' => null,
                'idEaresiF08' => null,
                'idExfidiF08' => null,
                'idIamF08' => null,
                'idLocalizacionLesionesF08' => null,
                'idPlanTratamientoF08' => null,
                'idSivimiF08' => null,
                'idSolicitudExamenesF08' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_f08', $this->id_f08);
        $criteria->compare('fecha_emision', $this->fecha_emision, true);
        $criteria->compare('id_iam_f08', $this->id_iam_f08);
        $criteria->compare('id_avieq_f08', $this->id_avieq_f08);
        $criteria->compare('id_apyf_f08', $this->id_apyf_f08);
        $criteria->compare('id_earesi_f08', $this->id_earesi_f08);
        $criteria->compare('id_sivimi_f08', $this->id_sivimi_f08);
        $criteria->compare('id_exfidi_f08', $this->id_exfidi_f08);
        $criteria->compare('id_localizacion_lesiones_f08', $this->id_localizacion_lesiones_f08);
        $criteria->compare('id_emergencia_obstetrica_f08', $this->id_emergencia_obstetrica_f08);
        $criteria->compare('id_solicitud_examenes_f08', $this->id_solicitud_examenes_f08);
        $criteria->compare('id_diagnostico_ingreso_f08', $this->id_diagnostico_ingreso_f08);
        $criteria->compare('id_plan_tratamiento_f08', $this->id_plan_tratamiento_f08);
        $criteria->compare('id_diagnostico_alta_f08', $this->id_diagnostico_alta_f08);
        $criteria->compare('id_alta_f08', $this->id_alta_f08);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}