<?php

/**
 * This is the model base class for the table "archivo.antecedentes_personales_familiares_f08".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AntecedentesPersonalesFamiliaresF08".
 *
 * Columns in table "archivo.antecedentes_personales_familiares_f08" available as properties of the model,
 * followed by relations of table "archivo.antecedentes_personales_familiares_f08" available as properties of the model.
 *
 * @property integer $id_apyf
 * @property boolean $alergico
 * @property boolean $clinico
 * @property boolean $ginecologico
 * @property boolean $traumatog
 * @property boolean $quirurgico
 * @property boolean $farmacologo
 * @property boolean $psiquiatrico
 * @property boolean $otro
 * @property string $observacion
 *
 * @property Ficha08[] $ficha08s
 */
abstract class BaseAntecedentesPersonalesFamiliaresF08 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'archivo.antecedentes_personales_familiares_f08';
    }

    public static function representingColumn() {
        return 'observacion';
    }

    public function rules() {
        return array(
            array('id_apyf', 'required'),
            array('id_apyf', 'numerical', 'integerOnly'=>true),
            array('alergico, clinico, ginecologico, traumatog, quirurgico, farmacologo, psiquiatrico, otro, observacion', 'safe'),
            array('alergico, clinico, ginecologico, traumatog, quirurgico, farmacologo, psiquiatrico, otro, observacion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_apyf, alergico, clinico, ginecologico, traumatog, quirurgico, farmacologo, psiquiatrico, otro, observacion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ficha08s' => array(self::HAS_MANY, 'Ficha08', 'id_apyf_f08'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_apyf' => Yii::t('app', 'Id Apyf'),
                'alergico' => Yii::t('app', 'Alergico'),
                'clinico' => Yii::t('app', 'Clinico'),
                'ginecologico' => Yii::t('app', 'Ginecologico'),
                'traumatog' => Yii::t('app', 'Traumatog'),
                'quirurgico' => Yii::t('app', 'Quirurgico'),
                'farmacologo' => Yii::t('app', 'Farmacologo'),
                'psiquiatrico' => Yii::t('app', 'Psiquiatrico'),
                'otro' => Yii::t('app', 'Otro'),
                'observacion' => Yii::t('app', 'Observacion'),
                'ficha08s' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_apyf', $this->id_apyf);
        $criteria->compare('alergico', $this->alergico);
        $criteria->compare('clinico', $this->clinico);
        $criteria->compare('ginecologico', $this->ginecologico);
        $criteria->compare('traumatog', $this->traumatog);
        $criteria->compare('quirurgico', $this->quirurgico);
        $criteria->compare('farmacologo', $this->farmacologo);
        $criteria->compare('psiquiatrico', $this->psiquiatrico);
        $criteria->compare('otro', $this->otro);
        $criteria->compare('observacion', $this->observacion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}