<?php

/**
 * This is the model base class for the table "archivo.alta_f08".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AltaF08".
 *
 * Columns in table "archivo.alta_f08" available as properties of the model,
 * followed by relations of table "archivo.alta_f08" available as properties of the model.
 *
 * @property integer $id_alta
 * @property boolean $domicilio
 * @property boolean $consulta_externa
 * @property boolean $observacion
 * @property boolean $internacion
 * @property boolean $referencia
 * @property boolean $egresa_vivo
 * @property boolean $condicion_estable
 * @property boolean $condicion_inestable
 * @property string $dias_de_incapacidad
 * @property string $sevicio_referencia
 * @property string $establecimiento
 * @property boolean $muerto_en_emergencia
 * @property string $causa
 * @property string $fecha
 * @property string $hora
 * @property string $nombre_del_profesional
 * @property string $firma
 * @property integer $numero_de_hoja
 *
 * @property Ficha08[] $ficha08s
 */
abstract class BaseAltaF08 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'archivo.alta_f08';
    }

    public static function representingColumn() {
        return 'dias_de_incapacidad';
    }

    public function rules() {
        return array(
            array('id_alta', 'required'),
            array('id_alta, numero_de_hoja', 'numerical', 'integerOnly'=>true),
            array('domicilio, consulta_externa, observacion, internacion, referencia, egresa_vivo, condicion_estable, condicion_inestable, dias_de_incapacidad, sevicio_referencia, establecimiento, muerto_en_emergencia, causa, fecha, hora, nombre_del_profesional, firma', 'safe'),
            array('domicilio, consulta_externa, observacion, internacion, referencia, egresa_vivo, condicion_estable, condicion_inestable, dias_de_incapacidad, sevicio_referencia, establecimiento, muerto_en_emergencia, causa, fecha, hora, nombre_del_profesional, firma, numero_de_hoja', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_alta, domicilio, consulta_externa, observacion, internacion, referencia, egresa_vivo, condicion_estable, condicion_inestable, dias_de_incapacidad, sevicio_referencia, establecimiento, muerto_en_emergencia, causa, fecha, hora, nombre_del_profesional, firma, numero_de_hoja', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ficha08s' => array(self::HAS_MANY, 'Ficha08', 'id_alta_f08'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_alta' => Yii::t('app', 'Id Alta'),
                'domicilio' => Yii::t('app', 'Domicilio'),
                'consulta_externa' => Yii::t('app', 'Consulta Externa'),
                'observacion' => Yii::t('app', 'Observacion'),
                'internacion' => Yii::t('app', 'Internacion'),
                'referencia' => Yii::t('app', 'Referencia'),
                'egresa_vivo' => Yii::t('app', 'Egresa Vivo'),
                'condicion_estable' => Yii::t('app', 'Condicion Estable'),
                'condicion_inestable' => Yii::t('app', 'Condicion Inestable'),
                'dias_de_incapacidad' => Yii::t('app', 'Dias De Incapacidad'),
                'sevicio_referencia' => Yii::t('app', 'Sevicio Referencia'),
                'establecimiento' => Yii::t('app', 'Establecimiento'),
                'muerto_en_emergencia' => Yii::t('app', 'Muerto En Emergencia'),
                'causa' => Yii::t('app', 'Causa'),
                'fecha' => Yii::t('app', 'Fecha'),
                'hora' => Yii::t('app', 'Hora'),
                'nombre_del_profesional' => Yii::t('app', 'Nombre Del Profesional'),
                'firma' => Yii::t('app', 'Firma'),
                'numero_de_hoja' => Yii::t('app', 'Numero De Hoja'),
                'ficha08s' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_alta', $this->id_alta);
        $criteria->compare('domicilio', $this->domicilio);
        $criteria->compare('consulta_externa', $this->consulta_externa);
        $criteria->compare('observacion', $this->observacion);
        $criteria->compare('internacion', $this->internacion);
        $criteria->compare('referencia', $this->referencia);
        $criteria->compare('egresa_vivo', $this->egresa_vivo);
        $criteria->compare('condicion_estable', $this->condicion_estable);
        $criteria->compare('condicion_inestable', $this->condicion_inestable);
        $criteria->compare('dias_de_incapacidad', $this->dias_de_incapacidad, true);
        $criteria->compare('sevicio_referencia', $this->sevicio_referencia, true);
        $criteria->compare('establecimiento', $this->establecimiento, true);
        $criteria->compare('muerto_en_emergencia', $this->muerto_en_emergencia);
        $criteria->compare('causa', $this->causa, true);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('hora', $this->hora, true);
        $criteria->compare('nombre_del_profesional', $this->nombre_del_profesional, true);
        $criteria->compare('firma', $this->firma, true);
        $criteria->compare('numero_de_hoja', $this->numero_de_hoja);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}