<?php

/**
 * This is the model base class for the table "archivo.avieq_f08".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AvieqF08".
 *
 * Columns in table "archivo.avieq_f08" available as properties of the model,
 * followed by relations of table "archivo.avieq_f08" available as properties of the model.
 *
 * @property integer $id_avieq
 * @property string $lugar_evento
 * @property string $direccion_evento
 * @property boolean $custodia_policial
 * @property boolean $accidente_transito
 * @property boolean $caida
 * @property boolean $quemadura
 * @property boolean $mordedura
 * @property boolean $ahogamiento
 * @property boolean $cuerpo_extrano
 * @property boolean $aplastamiento
 * @property boolean $violencia_arma_fuego
 * @property boolean $violencia_arma_cpunzante
 * @property boolean $otro_accidente
 * @property boolean $violencia_rina
 * @property boolean $violencia_familiar
 * @property boolean $abuso_fisico
 * @property boolean $abuso_psicologico
 * @property boolean $abuso_sexual
 * @property boolean $otra_violencia
 * @property boolean $intoxicacion_alcoholica
 * @property boolean $intoxicacion_alimentaria
 * @property boolean $intoxicacion_drogas
 * @property boolean $inhalacion_de_gases
 * @property boolean $otra_intoxicacion
 * @property boolean $envenenamiento
 * @property boolean $picadura
 * @property boolean $anafilaxia
 * @property string $observaciones
 * @property boolean $aliento_etilico
 * @property integer $valor_alcocheck
 * @property string $fecha_hora_evento
 *
 * @property Ficha08[] $ficha08s
 */
abstract class BaseAvieqF08 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'archivo.avieq_f08';
    }

    public static function representingColumn() {
        return 'lugar_evento';
    }

    public function rules() {
        return array(
            array('valor_alcocheck', 'numerical', 'integerOnly'=>true),
            array('lugar_evento, direccion_evento, custodia_policial, accidente_transito, caida, quemadura, mordedura, ahogamiento, cuerpo_extrano, aplastamiento, violencia_arma_fuego, violencia_arma_cpunzante, otro_accidente, violencia_rina, violencia_familiar, abuso_fisico, abuso_psicologico, abuso_sexual, otra_violencia, intoxicacion_alcoholica, intoxicacion_alimentaria, intoxicacion_drogas, inhalacion_de_gases, otra_intoxicacion, envenenamiento, picadura, anafilaxia, observaciones, aliento_etilico, fecha_hora_evento', 'safe'),
            array('lugar_evento, direccion_evento, custodia_policial, accidente_transito, caida, quemadura, mordedura, ahogamiento, cuerpo_extrano, aplastamiento, violencia_arma_fuego, violencia_arma_cpunzante, otro_accidente, violencia_rina, violencia_familiar, abuso_fisico, abuso_psicologico, abuso_sexual, otra_violencia, intoxicacion_alcoholica, intoxicacion_alimentaria, intoxicacion_drogas, inhalacion_de_gases, otra_intoxicacion, envenenamiento, picadura, anafilaxia, observaciones, aliento_etilico, valor_alcocheck, fecha_hora_evento', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_avieq, lugar_evento, direccion_evento, custodia_policial, accidente_transito, caida, quemadura, mordedura, ahogamiento, cuerpo_extrano, aplastamiento, violencia_arma_fuego, violencia_arma_cpunzante, otro_accidente, violencia_rina, violencia_familiar, abuso_fisico, abuso_psicologico, abuso_sexual, otra_violencia, intoxicacion_alcoholica, intoxicacion_alimentaria, intoxicacion_drogas, inhalacion_de_gases, otra_intoxicacion, envenenamiento, picadura, anafilaxia, observaciones, aliento_etilico, valor_alcocheck, fecha_hora_evento', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ficha08s' => array(self::HAS_MANY, 'Ficha08', 'id_avieq_f08'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_avieq' => Yii::t('app', 'Id Avieq'),
                'lugar_evento' => Yii::t('app', 'Lugar Evento'),
                'direccion_evento' => Yii::t('app', 'Direccion Evento'),
                'custodia_policial' => Yii::t('app', 'Custodia Policial'),
                'accidente_transito' => Yii::t('app', 'Accidente Transito'),
                'caida' => Yii::t('app', 'Caida'),
                'quemadura' => Yii::t('app', 'Quemadura'),
                'mordedura' => Yii::t('app', 'Mordedura'),
                'ahogamiento' => Yii::t('app', 'Ahogamiento'),
                'cuerpo_extrano' => Yii::t('app', 'Cuerpo Extrano'),
                'aplastamiento' => Yii::t('app', 'Aplastamiento'),
                'violencia_arma_fuego' => Yii::t('app', 'Violencia Arma Fuego'),
                'violencia_arma_cpunzante' => Yii::t('app', 'Violencia Arma Cpunzante'),
                'otro_accidente' => Yii::t('app', 'Otro Accidente'),
                'violencia_rina' => Yii::t('app', 'Violencia Rina'),
                'violencia_familiar' => Yii::t('app', 'Violencia Familiar'),
                'abuso_fisico' => Yii::t('app', 'Abuso Fisico'),
                'abuso_psicologico' => Yii::t('app', 'Abuso Psicologico'),
                'abuso_sexual' => Yii::t('app', 'Abuso Sexual'),
                'otra_violencia' => Yii::t('app', 'Otra Violencia'),
                'intoxicacion_alcoholica' => Yii::t('app', 'Intoxicacion Alcoholica'),
                'intoxicacion_alimentaria' => Yii::t('app', 'Intoxicacion Alimentaria'),
                'intoxicacion_drogas' => Yii::t('app', 'Intoxicacion Drogas'),
                'inhalacion_de_gases' => Yii::t('app', 'Inhalacion De Gases'),
                'otra_intoxicacion' => Yii::t('app', 'Otra Intoxicacion'),
                'envenenamiento' => Yii::t('app', 'Envenenamiento'),
                'picadura' => Yii::t('app', 'Picadura'),
                'anafilaxia' => Yii::t('app', 'Anafilaxia'),
                'observaciones' => Yii::t('app', 'Observaciones'),
                'aliento_etilico' => Yii::t('app', 'Aliento Etilico'),
                'valor_alcocheck' => Yii::t('app', 'Valor Alcocheck'),
                'fecha_hora_evento' => Yii::t('app', 'Fecha Hora Evento'),
                'ficha08s' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_avieq', $this->id_avieq);
        $criteria->compare('lugar_evento', $this->lugar_evento, true);
        $criteria->compare('direccion_evento', $this->direccion_evento, true);
        $criteria->compare('custodia_policial', $this->custodia_policial);
        $criteria->compare('accidente_transito', $this->accidente_transito);
        $criteria->compare('caida', $this->caida);
        $criteria->compare('quemadura', $this->quemadura);
        $criteria->compare('mordedura', $this->mordedura);
        $criteria->compare('ahogamiento', $this->ahogamiento);
        $criteria->compare('cuerpo_extrano', $this->cuerpo_extrano);
        $criteria->compare('aplastamiento', $this->aplastamiento);
        $criteria->compare('violencia_arma_fuego', $this->violencia_arma_fuego);
        $criteria->compare('violencia_arma_cpunzante', $this->violencia_arma_cpunzante);
        $criteria->compare('otro_accidente', $this->otro_accidente);
        $criteria->compare('violencia_rina', $this->violencia_rina);
        $criteria->compare('violencia_familiar', $this->violencia_familiar);
        $criteria->compare('abuso_fisico', $this->abuso_fisico);
        $criteria->compare('abuso_psicologico', $this->abuso_psicologico);
        $criteria->compare('abuso_sexual', $this->abuso_sexual);
        $criteria->compare('otra_violencia', $this->otra_violencia);
        $criteria->compare('intoxicacion_alcoholica', $this->intoxicacion_alcoholica);
        $criteria->compare('intoxicacion_alimentaria', $this->intoxicacion_alimentaria);
        $criteria->compare('intoxicacion_drogas', $this->intoxicacion_drogas);
        $criteria->compare('inhalacion_de_gases', $this->inhalacion_de_gases);
        $criteria->compare('otra_intoxicacion', $this->otra_intoxicacion);
        $criteria->compare('envenenamiento', $this->envenenamiento);
        $criteria->compare('picadura', $this->picadura);
        $criteria->compare('anafilaxia', $this->anafilaxia);
        $criteria->compare('observaciones', $this->observaciones, true);
        $criteria->compare('aliento_etilico', $this->aliento_etilico);
        $criteria->compare('valor_alcocheck', $this->valor_alcocheck);
        $criteria->compare('fecha_hora_evento', $this->fecha_hora_evento, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}