<?php

/**
 * This is the model base class for the table "archivo.emergencia_obstetrica_f08".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmergenciaObstetricaF08".
 *
 * Columns in table "archivo.emergencia_obstetrica_f08" available as properties of the model,
 * followed by relations of table "archivo.emergencia_obstetrica_f08" available as properties of the model.
 *
 * @property integer $id_emergencia_obstetrica
 * @property integer $gestas
 * @property integer $partos
 * @property integer $abortos
 * @property integer $cesareas
 * @property string $fecha_ultima_menstruacion
 * @property integer $semanas_gestacion
 * @property boolean $movimiento_fetal
 * @property string $frecuencia_c_fetal
 * @property boolean $membranas_rotas
 * @property integer $tiempo
 * @property string $altura_uterina
 * @property string $presentacion
 * @property string $dilatacion
 * @property string $borramiento
 * @property string $plano
 * @property boolean $pelvis_util
 * @property boolean $sangrado_vaginal
 * @property string $contracciones
 * @property string $observacion
 *
 * @property Ficha08[] $ficha08s
 */
abstract class BaseEmergenciaObstetricaF08 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'archivo.emergencia_obstetrica_f08';
    }

    public static function representingColumn() {
        return 'fecha_ultima_menstruacion';
    }

    public function rules() {
        return array(
            array('gestas, partos, abortos, cesareas, semanas_gestacion, tiempo', 'numerical', 'integerOnly'=>true),
            array('fecha_ultima_menstruacion, movimiento_fetal, frecuencia_c_fetal, membranas_rotas, altura_uterina, presentacion, dilatacion, borramiento, plano, pelvis_util, sangrado_vaginal, contracciones, observacion', 'safe'),
            array('gestas, partos, abortos, cesareas, fecha_ultima_menstruacion, semanas_gestacion, movimiento_fetal, frecuencia_c_fetal, membranas_rotas, tiempo, altura_uterina, presentacion, dilatacion, borramiento, plano, pelvis_util, sangrado_vaginal, contracciones, observacion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_emergencia_obstetrica, gestas, partos, abortos, cesareas, fecha_ultima_menstruacion, semanas_gestacion, movimiento_fetal, frecuencia_c_fetal, membranas_rotas, tiempo, altura_uterina, presentacion, dilatacion, borramiento, plano, pelvis_util, sangrado_vaginal, contracciones, observacion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ficha08s' => array(self::HAS_MANY, 'Ficha08', 'id_emergencia_obstetrica_f08'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_emergencia_obstetrica' => Yii::t('app', 'Id Emergencia Obstetrica'),
                'gestas' => Yii::t('app', 'Gestas'),
                'partos' => Yii::t('app', 'Partos'),
                'abortos' => Yii::t('app', 'Abortos'),
                'cesareas' => Yii::t('app', 'Cesareas'),
                'fecha_ultima_menstruacion' => Yii::t('app', 'Fecha Ultima Menstruacion'),
                'semanas_gestacion' => Yii::t('app', 'Semanas Gestacion'),
                'movimiento_fetal' => Yii::t('app', 'Movimiento Fetal'),
                'frecuencia_c_fetal' => Yii::t('app', 'Frecuencia C Fetal'),
                'membranas_rotas' => Yii::t('app', 'Membranas Rotas'),
                'tiempo' => Yii::t('app', 'Tiempo'),
                'altura_uterina' => Yii::t('app', 'Altura Uterina'),
                'presentacion' => Yii::t('app', 'Presentacion'),
                'dilatacion' => Yii::t('app', 'Dilatacion'),
                'borramiento' => Yii::t('app', 'Borramiento'),
                'plano' => Yii::t('app', 'Plano'),
                'pelvis_util' => Yii::t('app', 'Pelvis Util'),
                'sangrado_vaginal' => Yii::t('app', 'Sangrado Vaginal'),
                'contracciones' => Yii::t('app', 'Contracciones'),
                'observacion' => Yii::t('app', 'Observacion'),
                'ficha08s' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_emergencia_obstetrica', $this->id_emergencia_obstetrica);
        $criteria->compare('gestas', $this->gestas);
        $criteria->compare('partos', $this->partos);
        $criteria->compare('abortos', $this->abortos);
        $criteria->compare('cesareas', $this->cesareas);
        $criteria->compare('fecha_ultima_menstruacion', $this->fecha_ultima_menstruacion, true);
        $criteria->compare('semanas_gestacion', $this->semanas_gestacion);
        $criteria->compare('movimiento_fetal', $this->movimiento_fetal);
        $criteria->compare('frecuencia_c_fetal', $this->frecuencia_c_fetal, true);
        $criteria->compare('membranas_rotas', $this->membranas_rotas);
        $criteria->compare('tiempo', $this->tiempo);
        $criteria->compare('altura_uterina', $this->altura_uterina, true);
        $criteria->compare('presentacion', $this->presentacion, true);
        $criteria->compare('dilatacion', $this->dilatacion, true);
        $criteria->compare('borramiento', $this->borramiento, true);
        $criteria->compare('plano', $this->plano, true);
        $criteria->compare('pelvis_util', $this->pelvis_util);
        $criteria->compare('sangrado_vaginal', $this->sangrado_vaginal);
        $criteria->compare('contracciones', $this->contracciones, true);
        $criteria->compare('observacion', $this->observacion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}