<?php

/**
 * This is the model base class for the table "archivo.diagnostico_ingreso_f08".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DiagnosticoIngresoF08".
 *
 * Columns in table "archivo.diagnostico_ingreso_f08" available as properties of the model,
 * followed by relations of table "archivo.diagnostico_ingreso_f08" available as properties of the model.
 *
 * @property integer $id_diagnostico_ingreso
 * @property integer $cie
 * @property integer $presuntivo
 * @property integer $definitivo
 *
 * @property Ficha08[] $ficha08s
 */
abstract class BaseDiagnosticoIngresoF08 extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'archivo.diagnostico_ingreso_f08';
    }

    public static function representingColumn() {
        return 'id_diagnostico_ingreso';
    }

    public function rules() {
        return array(
            array('id_diagnostico_ingreso', 'required'),
            array('id_diagnostico_ingreso, cie, presuntivo, definitivo', 'numerical', 'integerOnly'=>true),
            array('cie, presuntivo, definitivo', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_diagnostico_ingreso, cie, presuntivo, definitivo', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ficha08s' => array(self::HAS_MANY, 'Ficha08', 'id_diagnostico_ingreso_f08'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_diagnostico_ingreso' => Yii::t('app', 'Id Diagnostico Ingreso'),
                'cie' => Yii::t('app', 'Cie'),
                'presuntivo' => Yii::t('app', 'Presuntivo'),
                'definitivo' => Yii::t('app', 'Definitivo'),
                'ficha08s' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_diagnostico_ingreso', $this->id_diagnostico_ingreso);
        $criteria->compare('cie', $this->cie);
        $criteria->compare('presuntivo', $this->presuntivo);
        $criteria->compare('definitivo', $this->definitivo);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'ActiveRecordRelation' => array(
                'class' => 'EActiveRecordRelationBehavior',
            ),
        ), parent::behaviors());
    }
}